### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by DoofyAss** [P5yl0/TeraEmulator_1725#2]
:disappointed:

![2018 07 28 - 08 55 55](https://user-images.githubusercontent.com/39556120/43348120-39ec2b52-9244-11e8-8a51-652c70cbf3d9.png)

**Comment by mrblackvein** [comment]
Okay dude, I found server with mysql old driver, then `mysql_connect` does work. Thank you :kissing_closed_eyes:

**Comment by P5yl0** [comment]
if you need a working launcher... 
i can pack you the latest working version i worked on...
no need for any extra files, just the serverlist files...
but the auth.php files need maybe some little edits, i have them working with Sha1 encryption for password, and servers use mostly md5, and maybe just 1-2 edits for username account database

ill put them on my website in near time with a little tutorial if you cna wait else, i can up them without edits and tutorial to mega..
